[workspace]
authors = ["3nrique0 <3nrique.0@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "devocgen_workshop_installs"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks.install_rzooroh]
description = "Install the RZooRoH package from CRAN"
cmd = """
Rscript -e "install.packages('RZooRoH', repos='https://cloud.r-project.org')"
"""

[tasks.test_rlibs]
description = "Test if the required libraries installed from CRAN are loaded properly"
cmd = """
R -e "library('RZooRoH'); print('Package loaded successfully')"
"""

[dependencies]
r-base = ">=4.5.2,<4.6"
r-essentials = ">=4.5,<5"
plink = ">=1.90b7.7,<2"
samtools = ">=1.22.1,<2"
bcftools = ">=1.22,<2"
