[workspace]
authors = ["3nrique0 <3nrique.0@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "devocgen_workshop_installs"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks.test_rlibs]
description = "Test if the required libraries installed from CRAN are loaded properly"
cmd = """
R -q -s --vanilla -e "library('RZooRoH'); print('Package RZooRoH loaded successfully');
     packageVersion('RZooRoH');
     library('SNPRelate'); print('Package SNPRelate loaded successfully');
     packageVersion('SNPRelate');"
"""

[tasks.install_rlibs]
description = "Test if the required libraries installed from CRAN are loaded properly"
cmd = """
R -q -s -e "options(repos = c(CRAN = 'https://cloud.r-project.org'))
    if (!require('BiocManager', quietly = TRUE))
    install.packages('BiocManager')
    BiocManager::install(version = '3.22')
    BiocManager::install('RZooRoH', force = TRUE)
    BiocManager::install('SNPRelate', force = TRUE)"
"""

[dependencies]
r-base = ">=4.5.2,<4.6"
r-essentials = ">=4.5,<5"
plink = ">=1.90b7.7,<2"
