[workspace]
authors = ["3nrique0 <3nrique.0@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "ws_slim"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
jupyterlab = ">=4.4.10,<5"
slim = ">=5.1,<6"
tskit = ">=0.6.4,<0.7"
msprime = ">=1.3.4,<2"
