[workspace]
authors = ["3nrique0 <3nrique.0@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "ws_slim"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
jupyterlab = ">=4.4.10,<5"
slim = ">=5.1,<6"
tskit = ">=1.0.0,<2"
msprime = ">=1.3.4,<2"
pyslim = ">=1.1.0,<2"
numpy = ">=2.3.5,<3"
matplotlib = ">=3.10.8,<4"
scipy = ">=1.16.3,<2"
pandas = ">=2.3.3,<3"
seaborn = ">=0.13.2,<0.14"
ipywidgets = ">=8.1.8,<9"
jupyter = ">=1.1.1,<2"
ipython = ">=9.7.0,<10"
