[workspace]
authors = ["3nrique0 <3nrique.0@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "ws_snif"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
scipy = ">=1.16.3,<2"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.3.4,<3"

