[workspace]
authors = ["3nrique0 <3nrique.0@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "ws_selnetime"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake-minimal = ">=9.13.7,<10"
matplotlib = ">=3.10.7,<4"
graphviz = ">=13.1.2,<14"
scipy = ">=1.16.3,<2"
sympy = ">=1.14.0,<2"
numba = ">=0.62.1,<0.63"
pandas = ">=2.3.3,<3"
tbb = ">=2022.3.0,<2023"
r-base = ">=4.5.2,<4.6"
r-essentials = ">=4.5,<5"
r-tidyverse = ">=2.0.0,<3"
r-scales = ">=1.4.0,<2"
r-patchwork = ">=1.3.2,<2"

[pypi-dependencies]
selnetime = ">=0.3.2, <0.4"